### ISSUE TITLE
Populate room number list for search

### ISSUE THREAD

**Issue by salsajeries** [QuietRoomUAH/Quiet-Room-Frontend#11]
Currently on the "Room Info" page, the _Room Number_ input is a text input. The suggestion is to switch to a dropdown that lists all the room numbers for the selected building, since the user may not know what room numbers exist for the building.

Might require new API endpoint @balloman to see what rooms exist for each building

<img width="473" alt="image" src="https://github.com/QuietRoomUAH/Quiet-Room-Frontend/assets/91573855/d60868e3-a601-41ca-a70b-c37293e26a31">

**Comment by Qeolvdxu** [comment]
This should solve the reopening of #3 as well right?

**Comment by salsajeries** [comment]
Yes, but #3 has been resolved anyways

**Comment by balloman** [comment]
Well, the functionality is there
