### ISSUE TITLE
Add default state for Room Quick View

### ISSUE THREAD

**Issue by Qeolvdxu** [QuietRoomUAH/Quiet-Room-Frontend#3]
The current default state for the Room Quick View is the same as the loading state, so it looks like it is taking an infinite amount of time to load something when first loading the page.

**Comment by Qeolvdxu** [comment]
looks good, however when you search for something invalid it switching to the loading state even after it already detects the input is invalid.

![loading-bug](https://github.com/QuietRoomUAH/Quiet-Room-Frontend/assets/57072675/2c2f30c9-d819-4fc9-8afd-40897fb700e4)

**Comment by salsajeries** [comment]
Loading state has been fixed to return to "empty" state if the room DNE
