### ISSUE TITLE
Add 'current time' searching

### ISSUE THREAD

**Issue by Qeolvdxu** [QuietRoomUAH/Quiet-Room-Frontend#5]
It would be very nice to be able to search for what rooms are open "right now". 
Maybe this could be the default? #4

**Comment by salsajeries** [comment]
Added default day/time for available room search to current day and time:
IF Weekend: Default Monday
End Time: current time + 1 hr

Issue will remain open until feedback is provided

**Comment by salsajeries** [comment]
Closing issue, compromised on 1-hr default time range for the time being
